

FROM node:13.12.0-alpine as builder
EXPOSE 80
# set working directory
WORKDIR /app

COPY ./build /build
# start app
# add ap
EXPOSE 80
FROM nginx:latest 

COPY  --from=builder  /build /usr/share/nginx/html